# Generated by Django 6.0.2 on 2026-08-18 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0010_alter_user_platform_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=64)),
                ('event_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('module', models.CharField(blank=True, db_index=True, max_length=40)),
                ('feature', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('device', models.CharField(blank=True, max_length=16)),
                ('browser', models.CharField(blank=True, max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_name', 'created_at'], name='analytics_a_event_n_e2acee_idx'), models.Index(fields=['company', 'created_at'], name='analytics_a_company_92fdb5_idx')],
            },
        ),
    ]
