# Generated by Django 6.0.2 on 2026-07-16 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierrfq',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_rfqs', to='quotes.quotation'),
        ),
    ]
