# Generated by Django 6.0.2 on 2026-08-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignsend_emailsuppression'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
