# Generated by Django 6.0.2 on 2026-08-31 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_cost'),
        ('customers', '0007_customernote_contact'),
        ('identity', '0012_companycompliance_other_registrations'),
        ('notifications', '0003_smslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=64)),
                ('waba_id', models.CharField(blank=True, max_length=64)),
                ('display_number', models.CharField(blank=True, max_length=32)),
                ('access_token', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'WhatsApp connection',
            },
        ),
        migrations.RemoveConstraint(
            model_name='campaignsend',
            name='unique_campaign_recipient',
        ),
        migrations.AddField(
            model_name='campaign',
            name='wa_template_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='campaignsend',
            name='channel',
            field=models.CharField(default='email', max_length=12),
        ),
        migrations.AddField(
            model_name='campaignsend',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='campaignsend',
            name='wa_message_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='campaignsend',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name='campaignsend',
            constraint=models.UniqueConstraint(fields=('campaign', 'email', 'phone'), name='unique_campaign_recipient'),
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_connection', to='identity.company'),
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
