# Generated by Django 6.0.2 on 2026-08-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_whatsappconnection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsend',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignsend',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaignsend',
            name='wa_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
