# Generated by Django 6.0.2 on 2026-07-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqdocument',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='rfqdocument',
            name='customer_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rfqdocument',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='customers.customerdepartment'),
        ),
        migrations.AddField(
            model_name='rfqdocument',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_released', to='customers.customercontact'),
        ),
    ]
