from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("password/", views.change_password, name="change_password"),
    path("profile/", views.profile, name="profile"),
    # Customers — client organisations, departments, contacts
    path("customers/", views.customers_list, name="customers"),
    path("customers/new/", views.customer_create, name="customer_create"),
    path("customers/<uuid:pk>/", views.customer_detail, name="customer_detail"),
    path("customers/<uuid:pk>/edit/", views.customer_edit, name="customer_edit"),
    path("customers/<uuid:pk>/contacts/", views.customer_contact_save,
         name="customer_contact_save"),
    path("customers/<uuid:pk>/departments/", views.customer_department,
         name="customer_department"),
    path("contacts/<uuid:pk>/", views.customer_contact_detail,
         name="customer_contact_detail"),
    # Company profile — the identity every other module reads from
    path("company/", views.company_profile, name="company_profile"),
    path("company/hours/", views.company_hours_page, name="company_hours_page"),
    path("company/hours/save/", views.company_hours, name="company_hours"),
    path("company/bank/", views.company_bank, name="company_bank"),
    path("company/contacts/", views.company_contact, name="company_contact"),
    path("company/documents/", views.company_document, name="company_document"),
    # People — the company's own members, and the pool every work picker reads
    path("people/", views.people, name="people"),
    path("people/add/", views.people_add, name="people_add"),
    path("people/<uuid:pk>/", views.person_detail, name="person_detail"),
    path("people/<uuid:pk>/role/", views.people_role, name="people_role"),
    path("people/<uuid:pk>/status/", views.people_status, name="people_status"),
    path("", views.dashboard, name="dashboard"),
    path("projects/", views.projects_list, name="projects"),
    path("projects/new/", views.project_create, name="project_create"),
    path("projects/<uuid:pk>/", views.project_detail, name="project_detail"),
    path("projects/<uuid:pk>/readiness/", views.readiness_partial, name="readiness_partial"),
    path("projects/<uuid:pk>/override/", views.project_override, name="project_override"),
    path("projects/<uuid:pk>/progress-claim/", views.project_progress_claim,
         name="project_progress_claim"),
    path("compliance-items/<uuid:pk>/approve/", views.compliance_item_approve,
         name="compliance_item_approve"),
    # Quotations (view · review · edit · PDF)
    path("quotations/", views.quotations_list, name="quotations"),
    path("quotations/new/", views.quotation_new, name="quotation_new"),
    path("quotations/extract/", views.quotation_extract, name="quotation_extract"),
    path("quotations/<uuid:pk>/", views.quotation_detail, name="quotation_detail"),
    path("quotations/<uuid:pk>/edit/", views.quotation_new, name="quotation_edit"),
    path("quotations/<uuid:pk>/pdf/", views.quotation_pdf, name="quotation_pdf"),
    path("quotations/<uuid:pk>/excel/", views.quotation_excel, name="quotation_excel"),
    path("quotations/<uuid:pk>/po/extract/", views.quotation_po_extract,
         name="quotation_po_extract"),
    path("quotations/<uuid:pk>/header/", views.quotation_header, name="quotation_header"),
    path("quotations/<uuid:pk>/lines/", views.quotation_line, name="quotation_line"),
    path("quotations/<uuid:pk>/sections/", views.quotation_section,
         name="quotation_section"),
    path("quotations/<uuid:pk>/status/", views.quotation_transition,
         name="quotation_transition"),
    path("quotations/<uuid:pk>/revise/", views.quotation_revise, name="quotation_revise"),
    path("quotations/<uuid:pk>/po/", views.quotation_po, name="quotation_po"),
    path("quotations/<uuid:pk>/start-work/", views.quotation_start_work,
         name="quotation_start_work"),
    path("quotations/<uuid:pk>/award/", views.quotation_award, name="quotation_award"),
    path("quotations/<uuid:pk>/invoice/", views.quotation_create_invoice,
         name="quotation_create_invoice"),
    path("quotations/<uuid:pk>/delivery-note/", views.quotation_create_delivery,
         name="quotation_create_delivery"),
    path("commercial-documents/<uuid:pk>/", views.commercial_document_detail,
         name="commercial_document_detail"),
    path("commercial-documents/<uuid:pk>/pdf/", views.commercial_document_pdf,
         name="commercial_document_pdf"),
    path("commercial-documents/<uuid:pk>/excel/", views.commercial_document_excel,
         name="commercial_document_excel"),
    path("commercial-documents/<uuid:pk>/status/", views.commercial_document_transition,
         name="commercial_document_transition"),
    path("quotations/<uuid:pk>/suggest/", views.quotation_suggest,
         name="quotation_suggest"),
    path("quotations/<uuid:pk>/template/", views.quotation_template,
         name="quotation_template"),
    path("quotations/<uuid:pk>/lines/bulk/", views.quotation_lines_bulk,
         name="quotation_lines_bulk"),
    path("quotations/<uuid:pk>/lines/move/", views.quotation_line_move,
         name="quotation_line_move"),
    path("quotations/<uuid:pk>/documents/", views.quotation_document,
         name="quotation_document"),
    # Work Management Engine (Module 8) — one engine, many views
    path("jobs/", views.work_list, name="work"),
    path("jobs/new/", views.work_new, name="work_new"),
    path("jobs/<uuid:pk>/", views.work_detail, name="work_detail"),
    path("jobs/<uuid:pk>/operations/", views.work_operations, name="work_operations"),
    path("jobs/<uuid:pk>/start/", views.work_start, name="work_start"),
    path("jobs/<uuid:pk>/complete/", views.work_complete, name="work_complete"),
    path("jobs/<uuid:pk>/status/", views.work_transition, name="work_transition"),
    path("jobs/<uuid:pk>/subtasks/", views.work_subtask_add, name="work_subtask_add"),
    path("jobs/<uuid:pk>/checklist/", views.work_checklist_add, name="work_checklist_add"),
    path("jobs/<uuid:pk>/checklist/<uuid:item_id>/toggle/", views.work_checklist_toggle,
         name="work_checklist_toggle"),
    path("jobs/<uuid:pk>/comments/", views.work_comment_add, name="work_comment_add"),
    path("jobs/<uuid:pk>/files/", views.work_file_add, name="work_file_add"),
    path("jobs/<uuid:pk>/team/", views.work_member, name="work_member"),
    path("jobs/<uuid:pk>/link/", views.work_link, name="work_link"),
    path("jobs/<uuid:pk>/decompose/", views.work_decompose, name="work_decompose"),
    path("jobs/<uuid:pk>/decompose/apply/", views.work_decompose_apply,
         name="work_decompose_apply"),
    path("notifications/", views.notifications, name="notifications"),
    path("projects/<uuid:pk>/phases/", views.project_phase_add, name="project_phase_add"),
    # RFQ (front door)
    path("rfq/", views.rfq_list, name="rfq"),
    path("rfq/upload/", views.rfq_upload, name="rfq_upload"),
    path("rfq/<uuid:pk>/", views.rfq_detail, name="rfq_detail"),
    path("rfq/<uuid:pk>/approve/", views.rfq_approve, name="rfq_approve"),
    path("rfq/<uuid:pk>/lines/", views.rfq_line, name="rfq_line"),
    # Estimating
    path("estimates/", views.estimates_list, name="estimates"),
    path("estimates/<uuid:pk>/", views.estimate_detail, name="estimate_detail"),
    path("estimates/<uuid:pk>/approve/", views.estimate_approve, name="estimate_approve"),
    path("estimates/<uuid:pk>/revise/", views.estimate_revise, name="estimate_revise"),
    # Procurement
    path("procurement/", views.procurement_dashboard, name="procurement"),
    path("procurement/prices/", views.procurement_prices, name="procurement_prices"),
    path("suppliers/", views.suppliers_list, name="suppliers"),
    path("suppliers/new/", views.supplier_create, name="supplier_create"),
    path("suppliers/import/", views.supplier_import, name="supplier_import"),
    path("suppliers/import/confirm/", views.supplier_import_confirm,
         name="supplier_import_confirm"),
    path("suppliers/<uuid:pk>/", views.supplier_detail, name="supplier_detail"),
    path("suppliers/<uuid:pk>/edit/", views.supplier_edit, name="supplier_edit"),
    path("suppliers/<uuid:pk>/documents/", views.supplier_document,
         name="supplier_document"),
    # Products (procurement intelligence — built from the price ledger)
    path("products/", views.products_list, name="products"),
    path("products/<uuid:pk>/", views.product_detail, name="product_detail"),
    path("products/<uuid:pk>/edit/", views.product_edit, name="product_edit"),
    path("products/<uuid:pk>/alias/", views.product_alias, name="product_alias"),
    path("products/<uuid:pk>/merge/", views.product_merge, name="product_merge"),
    # Procurement requests (internal requisition → optional approval → purchase)
    path("requests/", views.requests_list, name="requests"),
    path("requests/new/", views.request_new, name="request_new"),
    path("requests/settings/", views.request_settings, name="request_settings"),
    path("requests/<uuid:pk>/", views.request_detail, name="request_detail"),
    path("requests/<uuid:pk>/approve/", views.request_approve, name="request_approve"),
    path("requests/<uuid:pk>/reject/", views.request_reject, name="request_reject"),
    path("requests/<uuid:pk>/fulfil/", views.request_fulfil, name="request_fulfil"),
    path("purchase-orders/", views.purchase_orders_list, name="purchase_orders"),
    path("purchase-orders/<uuid:pk>/", views.po_detail, name="po_detail"),
    path("purchase-orders/<uuid:pk>/approve/", views.po_approve, name="po_approve"),
    path("purchase-orders/<uuid:pk>/receive/", views.po_receive, name="po_receive"),
    # Commercial + AI
    path("commercial/", views.commercial, name="commercial"),
    path("invoices/<uuid:pk>/payment/", views.invoice_payment, name="invoice_payment"),
    path("lulama/", views.lulama, name="lulama"),
]
