# Generated by Django 6.0.2 on 2026-07-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_customerpurchaseorder_quotationdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
