# Generated by Django 6.0.2 on 2026-07-22 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_company_document_prefix'),
        ('quotes', '0004_quotation_vendor_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('invoice', 'Tax invoice'), ('delivery', 'Delivery note')], max_length=12)),
                ('number', models.CharField(max_length=48)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('driver', models.CharField(blank=True, max_length=120)),
                ('receiver_name', models.CharField(blank=True, max_length=120)),
                ('delivery_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_documents', to='quotes.customerpurchaseorder')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_documents', to='quotes.quotation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'number'), name='unique_commercial_doc_number')],
            },
        ),
    ]
