# Generated by Django 6.0.2 on 2026-07-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_commercialdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('finalized', 'Finalized'), ('sent', 'Sent')], default='draft', max_length=12),
        ),
    ]
