# Generated by Django 6.0.2 — Document Designer: per-company templates for
# quotation / tax invoice / delivery note, with per-document override FKs.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_company_prices_include_tax_and_more'),
        ('quotes', '0008_tenant_upload_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Tax invoice'), ('delivery', 'Delivery note')], max_length=12)),
                ('name', models.CharField(max_length=80)),
                ('base_layout', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('compact', 'Compact')], default='classic', max_length=12)),
                ('is_default', models.BooleanField(default=False)),
                ('is_builtin', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_type', '-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='commercialdocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.documenttemplate'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.documenttemplate'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['company', 'doc_type', 'is_default'], name='quotes_docu_company_c2e877_idx'),
        ),
    ]
