# Generated by Django 6.0.2 on 2026-08-11 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_account_token'),
        ('quotes', '0009_document_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='engine',
            field=models.CharField(choices=[('reportlab', 'LulaWorks (built-in)'), ('html', 'HTML / CSS')], default='reportlab', max_length=12),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='origin',
            field=models.CharField(choices=[('builtin', 'LulaWorks template'), ('custom', 'Custom'), ('imported', 'Imported')], default='builtin', max_length=12),
        ),
        migrations.CreateModel(
            name='DocumentTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('engine', models.CharField(choices=[('reportlab', 'LulaWorks (built-in)'), ('html', 'HTML / CSS')], default='reportlab', max_length=12)),
                ('base_layout', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('compact', 'Compact')], default='classic', max_length=12)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('design', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotes.documenttemplate')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template', '-version'],
            },
        ),
        migrations.AddField(
            model_name='commercialdocument',
            name='template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.documenttemplateversion'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.documenttemplateversion'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.documenttemplateversion'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['company', 'doc_type', 'archived_at'], name='quotes_docu_company_fcbbed_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='unique_template_version'),
        ),
    ]
