# Generated by Django 6.0.2 on 2026-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_template_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='family',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
