# Generated by Django 6.0.2 on 2026-08-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_commercialdocumentpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='engine',
            field=models.CharField(choices=[('reportlab', 'Lulaworks (built-in)'), ('html', 'HTML / CSS')], default='reportlab', max_length=12),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='origin',
            field=models.CharField(choices=[('builtin', 'Lulaworks template'), ('custom', 'Custom'), ('imported', 'Imported')], default='builtin', max_length=12),
        ),
        migrations.AlterField(
            model_name='documenttemplateversion',
            name='engine',
            field=models.CharField(choices=[('reportlab', 'Lulaworks (built-in)'), ('html', 'HTML / CSS')], default='reportlab', max_length=12),
        ),
    ]
