# Generated by Django 6.0.2 on 2026-09-03 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_alter_documenttemplate_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchaseorder',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customerpurchaseorder',
            name='site',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customerpurchaseorder',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_pos', to='quotes.quotation'),
        ),
    ]
