# Generated by Django 6.0.2 on 2026-10-01 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_backfill_default_language'),
        ('quotes', '0017_customerpurchaseorderline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialdocumentpayment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='commercialdocumentpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('company', 'idempotency_key'), name='uniq_payment_idempotency_key'),
        ),
    ]
