# Generated by Django 6.0.2 — Email & Notification platform: the EmailLog audit
# record for every outbound message (platform-level, optional company).

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0007_company_prices_include_tax_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=160)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('account', 'Account'), ('security', 'Security'), ('billing', 'Billing'), ('document', 'Document'), ('task', 'Task & approval'), ('crm', 'Customer communication'), ('system', 'System'), ('marketing', 'Marketing')], default='system', max_length=16)),
                ('html_body', models.TextField(blank=True)),
                ('text_body', models.TextField(blank=True)),
                ('attachment_names', models.JSONField(blank=True, default=list)),
                ('entity_type', models.CharField(blank=True, max_length=48)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='notificatio_company_292891_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_d84ea4_idx')],
            },
        ),
    ]
