# Generated by Django 6.0.2 — EmailLog.attachment_spec: how the worker rebuilds
# document attachments (e.g. a quotation PDF) from the source record at delivery.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='attachment_spec',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
