# Generated by Django 6.0.2 on 2026-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='ai_compliance_detection_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='ai_cost_estimation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='ai_language',
            field=models.CharField(default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='ai_provider',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='ai_response_style',
            field=models.CharField(default='concise', max_length=16),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='ai_suggestions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='ai_summaries_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='ai_task_generation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='date_format',
            field=models.CharField(default='d M Y', max_length=24),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='document_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='financial_year_start_month',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='language',
            field=models.CharField(default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='number_format',
            field=models.CharField(default='1 234,56', max_length=16),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='week_starts_on',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
