# Generated by Django 6.0.2 on 2026-07-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_companysettings_ai_compliance_detection_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='emergency_hours',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='emergency_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='emergency_support',
            field=models.BooleanField(default=False),
        ),
    ]
