# Generated by Django 6.0.2 on 2026-08-18 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_commercial_document_terms'),
        ('billing', '0004_planprice_subscription_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='LulaWorks', max_length=120)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('sales_email', models.EmailField(blank=True, max_length=254)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('terms_url', models.URLField(blank=True)),
                ('privacy_url', models.URLField(blank=True)),
                ('trial_days', models.PositiveSmallIntegerField(default=30)),
                ('starting_ai_credits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auto_welcome', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.plan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
