# Generated by Django 6.0.2 on 2026-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='default_currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
