# Generated by Django 6.0.2 on 2026-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_platformsettings_default_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='password_min_length',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
