# Generated by Django 6.0.2 on 2026-08-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_platformsettings_password_min_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='platform_name',
            field=models.CharField(default='Lulaworks', max_length=120),
        ),
    ]
