# Generated by Django 6.0.2 on 2026-10-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_platformsettings_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='ai_document_extraction_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
