# Generated by Django 6.0.2 on 2026-09-22 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('identity', '0018_backfill_default_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['company', 'subject_type', 'subject_id'], name='core_domain_company_027c7c_idx'),
        ),
    ]
