# Generated by Django 6.0.2 on 2026-07-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='origin',
            field=models.CharField(choices=[('rfq', 'RFQ / Tender'), ('manual', 'Manual task'), ('recurring', 'Recurring schedule'), ('customer_request', 'Customer request')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
        ),
    ]
