# Generated by Django 6.0.2 on 2026-07-29 13:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_work_engine_backfill'),
        ('identity', '0004_company_document_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='site_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='site_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('progress', 'Progress update'), ('time_event', 'Time & attendance'), ('fuel', 'Fuel purchase'), ('material', 'Material purchase'), ('expense', 'Other expense'), ('general', 'General / evidence')], default='progress', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('event', models.CharField(blank=True, max_length=80)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_accuracy_m', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('distance_m', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('location_flagged', models.BooleanField(default=False)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=80)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='ZAR', max_length=8)),
                ('extraction_status', models.CharField(choices=[('none', 'No document'), ('pending', 'Awaiting review'), ('confirmed', 'Confirmed')], default='none', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reports', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='execution.task')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='execution.taskreport'),
        ),
        migrations.CreateModel(
            name='TaskResourceAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('transport', 'Transport'), ('fuel_advance', 'Fuel advance'), ('toll', 'Toll fees'), ('food', 'Food allowance'), ('accommodation', 'Accommodation'), ('cash_advance', 'Cash advance'), ('purchase_budget', 'Purchase budget'), ('vehicle', 'Company vehicle'), ('equipment', 'Equipment'), ('ppe', 'PPE'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('is_monetary', models.BooleanField(default=True)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('issued', 'Issued'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='requested', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='execution.task')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskreport',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='execution.taskresourceallocation'),
        ),
        migrations.CreateModel(
            name='TaskReportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='execution.taskreport')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_items', to='execution.task')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['report', 'id'],
                'indexes': [models.Index(fields=['company', 'task'], name='execution_t_company_6ec03a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='taskresourceallocation',
            index=models.Index(fields=['company', 'task'], name='execution_t_company_c923f6_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreport',
            index=models.Index(fields=['company', 'task', 'kind'], name='execution_t_company_81340c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreport',
            index=models.Index(fields=['company', 'location_flagged'], name='execution_t_company_7a1b71_idx'),
        ),
    ]
