# Generated by Django 6.0.2 on 2026-07-30 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_work_execution_engine'),
        ('procurement', '0002_alter_supplierrfq_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='supplier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='procurement.supplier'),
        ),
    ]
