# Generated by Django 6.0.2 on 2026-08-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_taskreport_supplier_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='origin',
            field=models.CharField(choices=[('rfq', 'RFQ / Tender'), ('manual', 'Manual job'), ('project', 'Project'), ('customer_request', 'Customer request'), ('recurring', 'Recurring maintenance'), ('internal', 'Internal company job'), ('breakdown', 'Breakdown / emergency callout'), ('preventative', 'Preventative maintenance')], default='manual', max_length=20),
        ),
    ]
