# Generated by Django 6.0.2 on 2026-08-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_taskmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
