# Generated by Django 6.0.2 on 2026-08-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0012_taskreport_reviewed_at_taskreport_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('paused', 'Paused'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('quality_check', 'Quality check'), ('client_signoff', 'Client sign-off'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
