# Generated by Django 6.0.2 on 2026-08-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0014_taskreport_fuel_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='kind',
            field=models.CharField(choices=[('progress', 'Progress update'), ('time_event', 'Time & attendance'), ('fuel', 'Fuel purchase'), ('material', 'Material purchase'), ('meal', 'Meal / food'), ('expense', 'Other expense'), ('general', 'General / evidence')], default='progress', max_length=12),
        ),
    ]
