# Generated by Django 6.0.2 on 2026-08-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0015_alter_taskreport_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='kind',
            field=models.CharField(choices=[('progress', 'Progress update'), ('time_event', 'Time & attendance'), ('fuel', 'Fuel purchase'), ('material', 'Material purchase'), ('meal', 'Meal / food'), ('toll', 'Toll / transport'), ('accommodation', 'Accommodation'), ('expense', 'Other expense'), ('incident', 'Incident / safety'), ('delay', 'Delay / standing time'), ('general', 'General / evidence')], default='progress', max_length=16),
        ),
    ]
