# Generated by Django 6.0.2 on 2026-10-01 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0016_alter_taskreport_kind'),
        ('identity', '0018_backfill_default_language'),
        ('procurement', '0005_procurement_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='taskreport',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('company', 'idempotency_key'), name='uniq_attendance_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='taskreport',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('company', 'idempotency_key'), name='uniq_taskreport_idempotency_key'),
        ),
    ]
