# Generated by Django 6.0.2 on 2026-08-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
    ]
