# Generated by Django 6.0.2 on 2026-09-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_planprice_subscription_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='per_seat_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
