# Generated by Django 6.0.2 on 2026-09-22 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_per_seat_price'),
        ('identity', '0018_backfill_default_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('change_requested', 'Change requested'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('contract_ref', models.CharField(blank=True, max_length=40)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by_name', models.CharField(blank=True, max_length=200)),
                ('accepted_by_email', models.CharField(blank=True, max_length=254)),
                ('acceptance_method', models.CharField(blank=True, max_length=24)),
                ('acceptance_ref', models.CharField(blank=True, max_length=120)),
                ('acceptance_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('change_requested_at', models.DateTimeField(blank=True, null=True)),
                ('change_request_message', models.TextField(blank=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('provisioned_snapshot', models.JSONField(blank=True, default=dict)),
                ('provisioning_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('activated', 'Activated'), ('mismatch', 'Mismatch')], default='pending', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_agreements', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='billing.enterpriseagreement')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', '-version'],
                'indexes': [models.Index(fields=['company', 'status'], name='billing_ent_company_79a392_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'version'), name='uniq_agreement_company_version')],
            },
        ),
    ]
