# Generated by Django 6.0.2 on 2026-09-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_enterpriseinvoice_enterprisepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseagreement',
            name='change_type',
            field=models.CharField(choices=[('new', 'New contract'), ('renewal', 'Renewal'), ('amendment', 'Amendment'), ('expansion', 'Expansion')], default='new', max_length=12),
        ),
    ]
