# Generated by Django 6.0.2 on 2026-09-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_enterpriseagreement_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingtransaction',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
