# Generated by Django 6.0.2 on 2026-08-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costentry',
            name='source',
            field=models.CharField(choices=[('timesheets', 'Timesheets (labour)'), ('supplier_invoices', 'Supplier invoices (material)'), ('field_reports', 'Field reports (WES)'), ('expense', 'Expense'), ('variation', 'Variation'), ('manual', 'Manual adjustment')], default='manual', max_length=20),
        ),
    ]
