# Generated by Django 6.0.2 on 2026-08-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_field_reports_cost_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
