# Generated by Django 6.0.2 on 2026-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_invoice_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_name',
            field=models.CharField(default='VAT', max_length=24),
        ),
    ]
