# Generated by Django 6.0.2 on 2026-09-12 13:46

import apps.knowledge.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_companycompliance_other_registrations'),
        ('knowledge', '0004_historicaljob_importeddocument_job_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddocument',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='knowledge.importeddocument'),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.knowledge.models.history_import_upload_path),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('extracting', 'Extracting'), ('matching', 'Matching'), ('completed', 'Completed'), ('needs_review', 'Needs review'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='queued', max_length=16),
        ),
        migrations.AddIndex(
            model_name='importeddocument',
            index=models.Index(fields=['company', 'file_hash'], name='knowledge_i_company_8214ee_idx'),
        ),
        migrations.AddIndex(
            model_name='importeddocument',
            index=models.Index(fields=['batch', 'status'], name='knowledge_i_batch_i_340aac_idx'),
        ),
    ]
