# Generated by Django 6.0.2 on 2026-09-12 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_companycompliance_other_registrations'),
        ('knowledge', '0005_importeddocument_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedentity',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stagedentity',
            name='mentions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='stagedentity',
            index=models.Index(fields=['batch', 'kind', 'dedup_key'], name='knowledge_s_batch_i_84002e_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagedentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('dedup_key', ''), _negated=True)), fields=('batch', 'kind', 'dedup_key'), name='uniq_staged_entity_per_batch'),
        ),
    ]
