# Generated by Django 6.0.2 on 2026-09-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_stagedentity_dedup_key_stagedentity_mentions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddocument',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
