# Generated by Django 6.0.2 on 2026-09-18 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_backfill_default_language'),
        ('knowledge', '0007_importeddocument_document_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('purchase', 'Purchased (from supplier)'), ('supplier_quote', 'Supplier quote'), ('sale', 'Sold (to customer)'), ('quote', 'Quoted (to customer)')], max_length=16)),
                ('party_kind', models.CharField(blank=True, choices=[('supplier', 'Supplier'), ('customer', 'Customer')], max_length=12)),
                ('party_id', models.CharField(blank=True, max_length=64)),
                ('party_name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(max_length=300)),
                ('item_key', models.CharField(db_index=True, max_length=160)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('occurred_on', models.DateField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
            ],
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='occurred_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='work_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='historicaljob',
            index=models.Index(fields=['company', 'customer_id', 'status'], name='knowledge_h_company_a98058_idx'),
        ),
        migrations.AddField(
            model_name='historicallineitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.company'),
        ),
        migrations.AddField(
            model_name='historicallineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallineitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallineitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='knowledge.importeddocument'),
        ),
        migrations.AddField(
            model_name='historicallineitem',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='knowledge.historicaljob'),
        ),
        migrations.AddField(
            model_name='historicallineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='historicallineitem',
            index=models.Index(fields=['company', 'item_key', 'direction'], name='knowledge_h_company_215e14_idx'),
        ),
        migrations.AddIndex(
            model_name='historicallineitem',
            index=models.Index(fields=['company', 'party_kind', 'party_id'], name='knowledge_h_company_221c95_idx'),
        ),
        migrations.AddIndex(
            model_name='historicallineitem',
            index=models.Index(fields=['document'], name='knowledge_h_documen_8b72a5_idx'),
        ),
    ]
