# Generated by Django 6.0.2 on 2026-09-23 00:58

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_backfill_default_language'),
        ('knowledge', '0008_historicallineitem_historicaljob_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pg_trgm must exist before a gin_trgm_ops index can be created.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='historicaljob',
            index=django.contrib.postgres.indexes.GinIndex(fields=['customer_name'], name='histjob_customer_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='historicaljob',
            index=django.contrib.postgres.indexes.GinIndex(fields=['reference'], name='histjob_reference_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='historicaljob',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='histjob_title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
