# Generated by Django 6.0.2 on 2026-09-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=96)),
                ('calling_code', models.CharField(blank=True, max_length=8)),
                ('flag_emoji', models.CharField(blank=True, max_length=8)),
                ('region', models.CharField(blank=True, max_length=32)),
                ('sort_priority', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['sort_priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BankingFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_label', models.CharField(default='Branch code', max_length=48)),
                ('branch_hint', models.CharField(blank=True, max_length=160)),
                ('show_swift', models.BooleanField(default=False)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking_rule', to='reference.country')),
            ],
        ),
        migrations.CreateModel(
            name='AddressFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField(blank=True, default=list)),
                ('postal_label', models.CharField(default='Postal code', max_length=48)),
                ('postal_regex', models.CharField(blank=True, max_length=200)),
                ('postal_hint', models.CharField(blank=True, max_length=160)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_rule', to='reference.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_countries', to='reference.currency'),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=48)),
                ('bank_code', models.CharField(blank=True, max_length=24)),
                ('swift_bic', models.CharField(blank=True, max_length=11)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_major', models.BooleanField(default=False)),
                ('sort_priority', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='reference.country')),
            ],
            options={
                'ordering': ['country', 'sort_priority', 'name'],
                'constraints': [models.UniqueConstraint(fields=('country', 'name'), name='uniq_bank_country_name')],
            },
        ),
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='reference.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='reference.currency')),
            ],
            options={
                'ordering': ['country', '-is_default'],
                'constraints': [models.UniqueConstraint(fields=('country', 'currency'), name='uniq_country_currency')],
            },
        ),
    ]
