# Generated by Django 6.0.2 on 2026-09-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDocumentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('authority', models.CharField(blank=True, max_length=96)),
                ('required', models.BooleanField(default=False)),
                ('has_expiry', models.BooleanField(default=False)),
                ('sort_priority', models.IntegerField(default=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_rules', to='reference.country')),
            ],
            options={
                'ordering': ['country', 'sort_priority', 'key'],
                'constraints': [models.UniqueConstraint(fields=('country', 'key'), name='uniq_document_country_key')],
            },
        ),
        migrations.CreateModel(
            name='StatutoryRegistrationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=48)),
                ('label', models.CharField(max_length=96)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('authority', models.CharField(blank=True, max_length=96)),
                ('required', models.BooleanField(default=False)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('date', 'Date')], default='text', max_length=8)),
                ('column', models.CharField(blank=True, max_length=48)),
                ('validator', models.CharField(blank=True, max_length=200)),
                ('placeholder', models.CharField(blank=True, max_length=64)),
                ('sort_priority', models.IntegerField(default=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_rules', to='reference.country')),
            ],
            options={
                'ordering': ['country', 'sort_priority', 'key'],
                'constraints': [models.UniqueConstraint(fields=('country', 'key'), name='uniq_statutory_country_key')],
            },
        ),
    ]
