# Generated by Django 6.0.2 on 2026-09-15 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_countrydocumentrule_statutoryregistrationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('native_name', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('ltr', 'Left-to-right'), ('rtl', 'Right-to-left')], default='ltr', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('sort_priority', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=2)),
                ('date_format', models.CharField(default='d/m/Y', max_length=32)),
                ('number_decimal', models.CharField(default='.', max_length=1)),
                ('number_group', models.CharField(default=',', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='reference.language')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('sort_priority', models.IntegerField(default=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='reference.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='reference.language')),
            ],
            options={
                'ordering': ['country', '-is_default', 'sort_priority'],
                'constraints': [models.UniqueConstraint(fields=('country', 'language'), name='uniq_country_language')],
            },
        ),
    ]
