"""Quotation PDF — the customer-facing document (BUSINESS_WORKFLOW: quote sent to
the client). Pure-Python ReportLab (no system libraries), so it renders inside the
slim container. Selling price only — never cost or margin (Golden Rule at the
document boundary)."""

from io import BytesIO

from django.contrib.staticfiles import finders
from reportlab.lib import colors, utils
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

BRAND = colors.HexColor("#0E6E6E")


def _logo_flowable(max_h=16 * mm):
    """The real logo image if one has been dropped into static (web/logo.png);
    else None (the caller falls back to the company name as text)."""
    path = finders.find("web/logo.png")
    if not path:
        return None
    reader = utils.ImageReader(path)
    iw, ih = reader.getSize()
    return Image(path, width=max_h * iw / ih, height=max_h)


def quotation_pdf_bytes(quote) -> bytes:
    company = quote.company
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm,
                            leftMargin=18 * mm, rightMargin=18 * mm,
                            title=f"Quotation {quote.number}")
    styles = getSampleStyleSheet()
    h = styles["Heading1"]
    h.textColor = BRAND
    small = styles["BodyText"]
    muted = styles["BodyText"].clone("muted")
    muted.textColor = colors.HexColor("#5b6b6a")

    logo = _logo_flowable()
    story = [
        logo if logo is not None else Paragraph(company.name, h),
        Paragraph("QUOTATION", styles["Heading2"]),
        Spacer(1, 6 * mm),
    ]

    meta = [
        [Paragraph("<b>Quotation</b>", small), quote.number,
         Paragraph("<b>Date</b>", small), quote.created_at.strftime("%Y-%m-%d")],
        [Paragraph("<b>Client</b>", small), quote.client_name,
         Paragraph("<b>Valid until</b>", small),
         quote.validity_date.strftime("%Y-%m-%d") if quote.validity_date else "—"],
        [Paragraph("<b>Project</b>", small), quote.title or "—",
         Paragraph("<b>Site</b>", small), quote.site or "—"],
    ]
    meta_tbl = Table(meta, colWidths=[26 * mm, 62 * mm, 26 * mm, 60 * mm])
    meta_tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    story += [meta_tbl, Spacer(1, 8 * mm)]

    # Description must wrap within its column → wrap it in a Paragraph (plain
    # strings overflow reportlab table cells).
    cell = small.clone("cell")
    cell.fontSize = 9
    cell.leading = 11
    rows = [["#", "Description", "Qty", "Unit", "Unit price", "Line total"]]
    for ln in quote.lines.all():
        rows.append([str(ln.position), Paragraph(ln.description, cell), f"{ln.qty:g}",
                     ln.unit, f"R {ln.unit_price:,.2f}", f"R {ln.line_total:,.2f}"])
    if len(rows) == 1:
        rows.append(["", Paragraph("No line items.", cell), "", "", "", ""])

    tbl = Table(rows, colWidths=[10 * mm, 78 * mm, 16 * mm, 18 * mm, 26 * mm, 26 * mm],
                repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f2f6f6")]),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.HexColor("#dfe6e6")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story += [tbl, Spacer(1, 6 * mm)]

    totals = [
        ["Subtotal", f"R {quote.subtotal:,.2f}"],
        [f"VAT ({quote.vat_rate:g}%)", f"R {quote.vat_amount:,.2f}"],
        ["Total", f"R {quote.total:,.2f}"],
    ]
    tot_tbl = Table(totals, colWidths=[52 * mm, 34 * mm], hAlign="RIGHT")
    tot_tbl.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("LINEABOVE", (0, -1), (-1, -1), 0.8, BRAND),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    story += [tot_tbl, Spacer(1, 10 * mm)]

    if quote.notes:
        story += [Paragraph("<b>Notes</b>", small), Paragraph(quote.notes, muted),
                  Spacer(1, 6 * mm)]
    story.append(Paragraph(
        "Prices exclude items not listed above. E&amp;OE. "
        "Generated by LulaWorks.", muted))

    doc.build(story)
    return buf.getvalue()
