# Generated by Django 6.0.2 on 2026-09-21 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('identity', '0018_backfill_default_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('protocol', models.CharField(choices=[('saml', 'SAML 2.0'), ('oidc', 'OpenID Connect')], default='saml', max_length=8)),
                ('status', models.CharField(choices=[('not_configured', 'Not configured'), ('configured', 'Configured (draft)'), ('activation_requested', 'Activation requested')], default='not_configured', max_length=24)),
                ('saml_idp_entity_id', models.CharField(blank=True, max_length=300)),
                ('saml_idp_sso_url', models.URLField(blank=True, max_length=500)),
                ('saml_idp_x509_cert', models.TextField(blank=True)),
                ('oidc_issuer', models.URLField(blank=True, max_length=500)),
                ('oidc_client_id', models.CharField(blank=True, max_length=300)),
                ('allowed_domains', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company',), name='one_sso_config_per_company')],
            },
        ),
    ]
