# Generated by Django 6.0.2 on 2026-09-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_ssoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssoconfig',
            name='oidc_client_secret_enc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='status',
            field=models.CharField(choices=[('not_configured', 'Not configured'), ('configured', 'Configured (draft)'), ('activation_requested', 'Activation requested'), ('active', 'Active')], default='not_configured', max_length=24),
        ),
    ]
