# Generated by Django 6.0.2 on 2026-09-03 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_lead_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('document', 'Document'), ('checklist', 'Checklist'), ('email', 'Email')], default='document', max_length=12)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('related_feature', models.CharField(blank=True, max_length=80)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('problem', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(default='/start-free-trial/', max_length=300)),
                ('includes', models.JSONField(blank=True, default=list)),
                ('items', models.JSONField(blank=True, default=list)),
                ('samples', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('related_feature', models.CharField(blank=True, max_length=80)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('problem', models.TextField(blank=True)),
                ('explainer', models.TextField(blank=True)),
                ('inputs', models.JSONField(blank=True, default=list)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(default='/start-free-trial/', max_length=300)),
                ('compute_key', models.CharField(blank=True, max_length=140)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
