# Generated by Django 6.0.2 on 2026-07-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_backfill_from_client_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vendor_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='vendor_portal',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
