# Generated by Django 6.0.2 on 2026-08-11 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_crm_pipeline_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersite',
            name='physical_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customersite',
            name='safety_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customersite',
            name='site_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.customercontact'),
        ),
    ]
