# Generated by Django 6.0.2 on 2026-08-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customersite_physical_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernote',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_notes', to='customers.customercontact'),
        ),
    ]
