# Generated by Django 6.0.2 on 2026-09-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='interest',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
