# Generated by Django 6.0.2 on 2026-08-18 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_errorevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('account', 'Account & Login'), ('crm', 'CRM'), ('quotations', 'Quotations'), ('jobs', 'Jobs'), ('tasks', 'Tasks'), ('procurement', 'Procurement'), ('suppliers', 'Suppliers'), ('invoices', 'Invoices'), ('delivery_notes', 'Delivery Notes'), ('billing', 'Payments & Billing'), ('ai', 'AI'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('mobile', 'Mobile App'), ('technical', 'Technical Problem'), ('other', 'Other')], default='other', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['is_published', 'category'], name='support_kba_is_publ_05b3a2_idx')],
            },
        ),
    ]
