# Generated by Django 6.0.2 on 2026-07-16 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0002_prompttemplate'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_text', models.TextField()),
                ('agent', models.CharField(default='lulama', max_length=48)),
                ('prompt_version', models.CharField(default='v1', max_length=16)),
                ('provider', models.CharField(default='deterministic', max_length=24)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft (awaiting human review)'), ('approved', 'Approved by human'), ('rejected', 'Rejected by human')], default='draft', max_length=12)),
                ('entity_type', models.CharField(blank=True, max_length=48)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'approval_status'], name='ai_platform_company_642a9e_idx')],
            },
        ),
    ]
