# Generated by Django 6.0.2 — AIUsageLog gains task-routing + failover audit
# fields (task, prompt_name, request_id correlating attempts, error text).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0003_aiinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='prompt_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='request_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='task',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
