# Generated by Django 6.0.2 on 2026-08-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0005_ai_provider_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinteraction',
            name='agent',
            field=models.CharField(default='lulaai', max_length=48),
        ),
    ]
