# Generated by Django 6.0.2 on 2026-07-21 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='industries_served',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='mobile',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='operating_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='operating_provinces',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code_postal',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_same_as_physical',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='services_offered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='site_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='specialisations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='suburb',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_reference_no',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='vehicle_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='year_established',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=160)),
                ('account_number', models.CharField(max_length=40)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('cheque', 'Cheque / Current'), ('savings', 'Savings'), ('transmission', 'Transmission'), ('foreign', 'Foreign currency')], default='cheque', max_length=16)),
                ('swift_code', models.CharField(blank=True, max_length=16)),
                ('currency', models.CharField(default='ZAR', max_length=8)),
                ('is_default', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('invoice_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('report_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('letterhead', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('seal', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'company branding',
            },
        ),
        migrations.CreateModel(
            name='CompanyCompliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vat_registered', models.BooleanField(default=False)),
                ('income_tax_no', models.CharField(blank=True, max_length=32)),
                ('paye_no', models.CharField(blank=True, max_length=32)),
                ('uif_no', models.CharField(blank=True, max_length=32)),
                ('coida_no', models.CharField(blank=True, max_length=32)),
                ('coida_expiry', models.DateField(blank=True, null=True)),
                ('bbbee_level', models.CharField(blank=True, max_length=16)),
                ('bbbee_expiry', models.DateField(blank=True, null=True)),
                ('csd_supplier_no', models.CharField(blank=True, max_length=32)),
                ('cidb_grading', models.CharField(blank=True, max_length=16)),
                ('industry_certifications', models.JSONField(blank=True, default=list)),
                ('iso_certifications', models.JSONField(blank=True, default=list)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'company compliance',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=160)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('mobile', models.CharField(blank=True, max_length=32)),
                ('extension', models.CharField(blank=True, max_length=12)),
                ('preferred_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('mobile', 'Mobile'), ('whatsapp', 'WhatsApp')], default='email', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('doc_type', models.CharField(blank=True, max_length=40)),
                ('file', models.FileField(upload_to='company_docs/%Y/')),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
