# Generated by Django 6.0.2 on 2026-08-05 17:44

import apps.identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_company_document_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(default=apps.identity.models.default_currency, max_length=8),
        ),
        migrations.AlterField(
            model_name='company',
            name='timezone',
            field=models.CharField(default=apps.identity.models.default_timezone, max_length=64),
        ),
    ]
