# Generated by Django 6.0.2 on 2026-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_backfill_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='prices_include_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='reverse_charge_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_name',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
