# Generated by Django 6.0.2 on 2026-08-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_account_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('owner', 'Platform Owner'), ('admin', 'Platform Admin'), ('support', 'Support')], default='', max_length=16),
        ),
    ]
