# Generated by Django 6.0.2 on 2026-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_user_platform_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('owner', 'Platform Owner'), ('admin', 'Administration'), ('finance', 'Finance'), ('hr', 'People / HR'), ('support', 'Support')], default='', max_length=16),
        ),
    ]
