# Generated by Django 6.0.2 on 2026-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_company_receives_education_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycompliance',
            name='other_registrations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
