# Generated by Django 6.0.2 on 2026-09-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_companycompliance_other_registrations'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reference.bank'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='routing_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
