# Generated by Django 6.0.2 on 2026-09-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_normalize_phone_e164'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankaccount',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
