# Generated by Django 6.0.2 on 2026-09-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0016_companybankaccount_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_language',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='company',
            name='default_locale',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_locale',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
