# Generated by Django 6.0.2 on 2026-07-16 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('documentation', 'Documentation'), ('training', 'Training'), ('medical', 'Medical'), ('equipment', 'Equipment'), ('permit', 'Permit'), ('ppe', 'PPE'), ('induction', 'Induction'), ('insurance', 'Insurance')], max_length=16)),
                ('source', models.CharField(choices=[('customer', 'Customer requirement'), ('mine', 'Mine profile'), ('site', 'Site profile'), ('rfq', 'RFQ requirement'), ('contract', 'Contract'), ('work_type', 'Work-type library'), ('equipment', 'Equipment requirement'), ('policy', 'Company policy'), ('regulatory', 'Regulatory knowledge base'), ('ai', 'AI recommendation')], max_length=16)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('applies_when', models.JSONField(blank=True, default=dict)),
                ('default_valid_days', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('documentation', 'Documentation'), ('training', 'Training'), ('medical', 'Medical'), ('equipment', 'Equipment'), ('permit', 'Permit'), ('ppe', 'PPE'), ('induction', 'Induction'), ('insurance', 'Insurance')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('customer', 'Customer requirement'), ('mine', 'Mine profile'), ('site', 'Site profile'), ('rfq', 'RFQ requirement'), ('contract', 'Contract'), ('work_type', 'Work-type library'), ('equipment', 'Equipment requirement'), ('policy', 'Company policy'), ('regulatory', 'Regulatory knowledge base'), ('ai', 'AI recommendation')], max_length=16)),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='missing', max_length=12)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storagefile')),
            ],
            options={
                'ordering': ['project', 'category', 'name'],
            },
        ),
    ]
